# Dockerfile for React client

# Build react client
FROM node:18.15.0-alpine

# Working directory be app
WORKDIR /usr/src/benetton/client

COPY package*.json ./

# copy local files to letseat folder
COPY . .

###  Installing dependencies
RUN yarn install --silent

# Build project
RUN yarn build

EXPOSE 5001

CMD ["yarn","start"]