version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.server
    image: benetton-server
    container_name: benetton-container-server
    command: npm run start:dev
    volumes:
      - ./server/:/usr/src/benetton/server
      # - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    # depends_on:
    #   - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - benetton-network

  # mongo:
  #   image: mongo
  #   volumes:
  #     - benetton_db:/data/db
  #   ports:
  #     - "27017:27017"
  #   networks:
  #     - benetton-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    image: benetton-client
    container_name: benetton-container-client
    command: yarn start
    volumes:
      - ./client/:/usr/src/benetton/client
      # - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "5001:5001"
    networks:
      - benetton-network

networks:
  benetton-network:
    driver: bridge

# volumes:
#     data-volume:
#     node_modules:
#     web-root:
#       driver: local
