export const networkDrivesList = [
    'F:',
    'G:',
    'H:',
    'I:',
    'J:',
    'K:',
    'L:',
    'M:',
    'N:',
    'O:',
    'P:',
    'Q:',
    'R:',
    'S:',
    'T:',
    'U:',
    'V:',
    'W:',
    'X:',
    'Y:',
    'Z:'
]

export const softwaresList = [
    'Abaco',
    'Aive',
    'Assyst',
    'Atomos',
    'Beta',
    'CICS',
    'CQWeb',
    'Citrix',
    'Color Service',
    'DataColor',
    'E-Report',
    'EAS',
    'EasyMag',
    'Expert Plan',
    'GDDM',
    'GECO',
    'Ideale',
    'Intranet',
    'IRIS Textile',
    'Iris',
    'MicroStartegy',
    'Open Bee',
    'OpenBee',
    'Orgatex',
    'Orgatex',
    'Safe Paie',
    'SAP',
    'STEALTH',
    'TAGETIK',
    'TIM',
    'TTN',
    'Terminal',
    'TEXCUT',
    'Vison R11'
]


export const groupList = [
    'Achat',
    'Administration',
    'Audit',
    'Audit Soc et Envir',
    'Bon de Livraison',
    'CAD',
    'C.Qualité',
    'Campionnario',
    'Comptabilité',
    'Comptage Sahel',
    'Coupe',
    'Direction',
    'Export',
    'Finissage',
    'G.Gafsa',
    'G.Kasserine',
    'IT',
    'Indus',
    'Industrie',
    'LAV.Teint B1',
    'LAV.Teint B2',
    'Maintenance',
    'Mag Accessoire',
    'Mag MP',
    'Modelleria',
    'Personnel',
    'Planification',
    'Prog.Tessile',
    'Programmation',
    'Prototype',
    'Qualite Tessile',
    'Qualité',
    'Qualité Textile',
    'RH',
    'S.VM',
    'Securite',
    'Stock',
    'Teinture',
    'Transport',
    'Transit',
    'UTM'
]

