#  Dockerfile for Node Express Backend

FROM node:18.15.0-alpine

# Create App Directory
# RUN mkdir -p /usr/src/app
WORKDIR /usr/src/benetton/server

# Install Dependencies
COPY package*.json ./

RUN npm install --silent

# Copy app source code
COPY . .

# Creates a "dist" folder with the production build
RUN npm run build

# Exports
EXPOSE 3000

# Start the server using the production build
CMD [ "npm", "run", "start:dev" ]