export enum ComputerActionsTypes {
    FETCH_COMPUTERS_REQUEST = 'FETCH_COMPUTERS_REQUEST',
    FETCH_COMPUTERS_SUCCESS = 'FETCH_COMPUTERS_SUCCESS',
    FETCH_COMPUTERS_FAILURE = 'FETCH_COMPUTERS_FAILURE',

    CREATE_COMPUTER_REQUEST = 'CREATE_COMPUTER_REQUEST',
    CREATE_COMPUTER_SUCCESS = 'CREATE_COMPUTER_SUCCESS',
    CREATE_COMPUTER_FAILURE = 'CREATE_COMPUTER_FAILURE',
}