export enum PasswordActionsTypes {
    UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST',
    UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS',
    UPDATE_PASSWORD_FAILURE = 'UPDATE_PASSWORD_FAILURE',
}